env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: self-hosting-agent.bin
    id: self-hosting-agent
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml
      - deployment/self-hosting-agent.service
